# Store packages locally to allow caching.
variables:
  JULIA_DEPOT_PATH: ${CI_PROJECT_DIR}/.julia
  JULIA_NUM_THREADS: 2

# Cache packages per job (i.e. Julia version) and project specification.
# Do not cache Manifest.toml so that Julia still uses the most recent packages.
cache:
  key:
    prefix: ${CI_JOB_NAME}
    files:
      - Project.toml
  paths:
    - .julia/packages
    - .julia/compiled

test:
  image: julia:${JULIA_VERSION}
  script:
    - julia -e 'using InteractiveUtils; versioninfo()'
    - julia --project -e 'using Pkg; Pkg.build(); Pkg.test();'
  parallel:
    matrix:
      - JULIA_VERSION:
          - '1.4'
          - '1.5'
          - '1.6'
