# Store packages locally to allow caching.
variables:
  JULIA_DEPOT_PATH: ${CI_PROJECT_DIR}/.julia
  JULIA_NUM_THREADS: 2

# Cache packages per job (i.e. Julia version) and project specification.
# Do not cache Manifest.toml so that Julia still uses the most recent packages.
cache:
  key:
    prefix: ${CI_JOB_NAME}
    files:
      - Project.toml
  paths:
    - .julia/packages
    - .julia/compiled

.definitions:
  script: &script
    script:
      - julia -e '
          using InteractiveUtils;
          versioninfo()'
      - julia --project=@. -e '
          using Pkg;
          Pkg.build();
          Pkg.test();'

Julia 1.0:
  image: julia:1.0
  <<: *script

Julia 1.5:
  image: julia:1.5
  <<: *script

Julia 1.6:
  image: julia:1.6
  <<: *script
